# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64813a80ac3d1f298d1ba018aab852e69792561ea2e39f262f8bffa41c92de8dd7b276d68c3d7509b0093afd7ab4edbe59f89d2435edf36f30b1d980fa57dace

test:
  secret_key_base: c351a4cf3bbb54d2107527b78a4d3f548e3528755f1ce6fca087fd573063721309a60da97d226c5ef97fb4b03b06d5122f4ca6a541c0658d5aa9bcb82facb0bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
